# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle 构建 & 发布

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: 设置 JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: 验证 Gradle 包装器
      uses: gradle/wrapper-validation-action@v1

    - name: 提升 Gradle 包装器权限
      run: chmod +x ./gradlew
      
    - name: 设置 Gradle
      uses: gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc

    - name: Build
      env:
        CI: 'true'
      run: ./gradlew -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false --no-daemon --no-parallel --continue build

    - name: Upload build reports
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: build-reports
        path: '**/build/reports/'
